// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// AppInformation returns basic runtime information, message totals and latest release version.
func AppInformation(ctx context.Context, clientConfig ClientConfig) (interface{}, error) {

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", "/api/v1/info", &RequestOpts{
		OperationID: "AppInformation",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

// WebUIConfigurationResponse returns configuration settings for the web UI. Intended for web UI only!
func WebUIConfigurationResponse(ctx context.Context, clientConfig ClientConfig) (interface{}, error) {

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", "/api/v1/webui", &RequestOpts{
		OperationID: "WebUIConfigurationResponse",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
