// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type TestingNamespace struct {
	config ClientConfig
}

func NewTestingNamespace(config ClientConfig) *TestingNamespace {
	return &TestingNamespace{
		config: config,
	}
}

// GetChaos returns the current Chaos triggers configuration. This API route will return an error if Chaos is not enabled at runtime.
func (sdk *TestingNamespace) GetChaos(ctx context.Context) (interface{}, error) {
	return GetChaos(ctx, sdk.config)
}

// SetChaosParams set the Chaos triggers configuration and return the updated values. This API route will return an error if Chaos is not enabled at runtime. If any triggers are omitted from the request, then those are reset to their default values with a 0% probability (ie: disabled). Setting a blank `{}` will reset all triggers to their default values.
//
// Parameters:
//
//	authentication: Trigger for Chaos
//	recipient: Trigger for Chaos
//	sender: Trigger for Chaos
func (sdk *TestingNamespace) SetChaosParams(ctx context.Context, params SetChaosParamsParams) (interface{}, error) {
	return SetChaosParams(ctx, sdk.config, params)
}

// GetMessageHTMLParams renders just the message's HTML part which can be used for UI integration testing. Attached inline images are modified to link to the API provided they exist. Note that is the message does not contain a HTML part then an 404 error is returned. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	embed: If this is route is to be embedded in an iframe, set embed to `1` in
//	the URL to add `target="_blank"` and `rel="noreferrer noopener"` to all
//	links. In addition, a small script will be added to the end of the document
//	to post (postMessage()) the height of the document back to the parent window
//	for optional iframe height resizing. Note that this will also *transform*
//	the message into a full HTML document (if it isn't already), so this option
//	is useful for viewing but not programmatic testing.
func (sdk *TestingNamespace) GetMessageHTMLParams(ctx context.Context, params GetMessageHTMLParamsParams) (interface{}, error) {
	return GetMessageHTMLParams(ctx, sdk.config, params)
}

// GetMessageTextParams renders just the message's text part which can be used for UI integration testing. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func (sdk *TestingNamespace) GetMessageTextParams(ctx context.Context, params GetMessageTextParamsParams) (interface{}, error) {
	return GetMessageTextParams(ctx, sdk.config, params)
}

type ApplicationNamespace struct {
	config ClientConfig
}

func NewApplicationNamespace(config ClientConfig) *ApplicationNamespace {
	return &ApplicationNamespace{
		config: config,
	}
}

// AppInformation returns basic runtime information, message totals and latest release version.
func (sdk *ApplicationNamespace) AppInformation(ctx context.Context) (interface{}, error) {
	return AppInformation(ctx, sdk.config)
}

// WebUIConfigurationResponse returns configuration settings for the web UI. Intended for web UI only!
func (sdk *ApplicationNamespace) WebUIConfigurationResponse(ctx context.Context) (interface{}, error) {
	return WebUIConfigurationResponse(ctx, sdk.config)
}

type MessageNamespace struct {
	config ClientConfig
}

func NewMessageNamespace(config ClientConfig) *MessageNamespace {
	return &MessageNamespace{
		config: config,
	}
}

// GetParams returns the summary of a message, marking the message as read. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func (sdk *MessageNamespace) GetParams(ctx context.Context, params GetMessageParamsParams) (*Message, error) {
	return GetMessageParams(ctx, sdk.config, params)
}

// GetHeadersParams returns the message headers as an array. Note that header keys are returned alphabetically. The ID can be set to `latest` to return the latest message headers.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func (sdk *MessageNamespace) GetHeadersParams(ctx context.Context, params GetHeadersParamsParams) (interface{}, error) {
	return GetHeadersParams(ctx, sdk.config, params)
}

// AttachmentParams this will return the attachment part using the appropriate Content-Type. The ID can be set to `latest` to reference the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	partID: Attachment part ID
func (sdk *MessageNamespace) AttachmentParams(ctx context.Context, params AttachmentParamsParams) (interface{}, error) {
	return AttachmentParams(ctx, sdk.config, params)
}

// ThumbnailParams this will return a cropped 180x120 JPEG thumbnail of an image attachment. If the image is smaller than 180x120 then the image is padded. If the attachment is not an image then a blank image is returned. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	partID: Attachment part ID
func (sdk *MessageNamespace) ThumbnailParams(ctx context.Context, params ThumbnailParamsParams) (interface{}, error) {
	return ThumbnailParams(ctx, sdk.config, params)
}

// DownloadRawParams returns the full email source as plain text. The ID can be set to `latest` to return the latest message source.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func (sdk *MessageNamespace) DownloadRawParams(ctx context.Context, params DownloadRawParamsParams) (interface{}, error) {
	return DownloadRawParams(ctx, sdk.config, params)
}

// ReleaseParams release a message via a pre-configured external SMTP server. This is only enabled if message relaying has been configured. The ID can be set to `latest` to reference the latest message.
//
// Parameters:
//
//	iD: Message database ID
//	to: Array of email addresses to relay the message to
func (sdk *MessageNamespace) ReleaseParams(ctx context.Context, params ReleaseMessageParamsParams) (interface{}, error) {
	return ReleaseMessageParams(ctx, sdk.config, params)
}

// SendParams sends an email message through the HTTP API with sender, recipient, and message content details. Provide `From` with an `Email` address, and use `Attachments` for files encoded in base64. A 200 response includes the sent message's database ID.
//
// Send a message via the HTTP API.
//
// Parameters:
//
//	from: "From" recipient
//	attachments: Attachments
//	bcc: Bcc recipients email addresses only
//	cc: Cc recipients
//	hTML: Message body (HTML)
//	headers: Optional headers in {"key":"value"} format
//	replyTo: Optional Reply-To recipients
//	subject: Subject
//	tags: Mailpit tags
//	text: Message body (text)
//	to: "To" recipients
func (sdk *MessageNamespace) SendParams(ctx context.Context, params SendMessageParamsParams) (interface{}, error) {
	return SendMessageParams(ctx, sdk.config, params)
}

type OtherNamespace struct {
	config ClientConfig
}

func NewOtherNamespace(config ClientConfig) *OtherNamespace {
	return &OtherNamespace{
		config: config,
	}
}

// HTMLCheckParams returns the summary of the message HTML checker. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func (sdk *OtherNamespace) HTMLCheckParams(ctx context.Context, params HTMLCheckParamsParams) (*HTMLCheckResponse, error) {
	return HTMLCheckParams(ctx, sdk.config, params)
}

// LinkCheckParams returns the summary of the message Link checker. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	follow: Follow redirects
func (sdk *OtherNamespace) LinkCheckParams(ctx context.Context, params LinkCheckParamsParams) (*LinkCheckResponse, error) {
	return LinkCheckParams(ctx, sdk.config, params)
}

// SpamAssassinCheckParams returns the SpamAssassin summary (if enabled) of the message. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func (sdk *OtherNamespace) SpamAssassinCheckParams(ctx context.Context, params SpamAssassinCheckParamsParams) (*SpamAssassinResponse, error) {
	return SpamAssassinCheckParams(ctx, sdk.config, params)
}

type MessagesNamespace struct {
	config ClientConfig
}

func NewMessagesNamespace(config ClientConfig) *MessagesNamespace {
	return &MessagesNamespace{
		config: config,
	}
}

// GetParams returns messages from the mailbox ordered from newest to oldest.
//
// Parameters:
//
//	start: Pagination offset
//	limit: Limit number of results
func (sdk *MessagesNamespace) GetParams(ctx context.Context, params GetMessagesParamsParams) (interface{}, error) {
	return GetMessagesParams(ctx, sdk.config, params)
}

// SetReadStatusParams you can optionally provide an array of IDs or a search string. If neither IDs nor search is provided then all mailbox messages are updated.
//
// Parameters:
//
//	tz: Optional [timezone
//	identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
//	used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
//	iDs: Optional array of message database IDs
//	read: Read status
//	search: Optional messages matching a search
func (sdk *MessagesNamespace) SetReadStatusParams(ctx context.Context, params SetReadStatusParamsParams) (interface{}, error) {
	return SetReadStatusParams(ctx, sdk.config, params)
}

// DeleteParams delete individual or all messages. If no IDs are provided then all messages are deleted.
//
// Parameters:
//
//	iDs: Array of message database IDs
func (sdk *MessagesNamespace) DeleteParams(ctx context.Context, params DeleteMessagesParamsParams) (interface{}, error) {
	return DeleteMessagesParams(ctx, sdk.config, params)
}

// SearchParams returns messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/), sorted by received date (descending).
//
// Parameters:
//
//	query: Search query
//	start: Pagination offset
//	limit: Limit results
//	tz: Optional [timezone
//	identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
//	used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
func (sdk *MessagesNamespace) SearchParams(ctx context.Context, params SearchParamsParams) (interface{}, error) {
	return SearchParams(ctx, sdk.config, params)
}

// DeleteSearchParams delete all messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/).
//
// Parameters:
//
//	query: Search query
//	tz: [Timezone
//	identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
//	used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
func (sdk *MessagesNamespace) DeleteSearchParams(ctx context.Context, params DeleteSearchParamsParams) (interface{}, error) {
	return DeleteSearchParams(ctx, sdk.config, params)
}

type TagsNamespace struct {
	config ClientConfig
}

func NewTagsNamespace(config ClientConfig) *TagsNamespace {
	return &TagsNamespace{
		config: config,
	}
}

// GetAll lists all unique tags currently assigned to messages. Use this endpoint to retrieve the available tag values when you need to inspect message tags.
//
// Returns a JSON array of all unique message tags.
func (sdk *TagsNamespace) GetAll(ctx context.Context) (interface{}, error) {
	return GetAllTags(ctx, sdk.config)
}

// SetParams this will overwrite any existing tags for selected message database IDs. To remove all tags from a message, pass an empty tags array.
//
// Parameters:
//
//	iDs: Array of message database IDs
//	tags: Array of tag names to set
func (sdk *TagsNamespace) SetParams(ctx context.Context, params SetTagsParamsParams) (interface{}, error) {
	return SetTagsParams(ctx, sdk.config, params)
}

// RenameParams renames an existing tag. Use `Tag` to identify the tag and provide `Name` as its replacement name. The request body is optional, but when supplied it must include `Name`.
//
// Renames an existing tag.
//
// Parameters:
//
//	tag: The url-encoded tag name to rename
//	name: New name
func (sdk *TagsNamespace) RenameParams(ctx context.Context, params RenameTagParamsParams) (interface{}, error) {
	return RenameTagParams(ctx, sdk.config, params)
}

// DeleteParams deletes a tag. This will not delete any messages with the tag, but will remove the tag from any messages containing the tag.
//
// Parameters:
//
//	tag: The url-encoded tag name to delete
func (sdk *TagsNamespace) DeleteParams(ctx context.Context, params DeleteTagParamsParams) (interface{}, error) {
	return DeleteTagParams(ctx, sdk.config, params)
}

type Mailpit struct {
	Testing     *TestingNamespace
	Application *ApplicationNamespace
	Message     *MessageNamespace
	Other       *OtherNamespace
	Messages    *MessagesNamespace
	Tags        *TagsNamespace
}

func NewMailpit(config ClientConfig) *Mailpit {
	return &Mailpit{
		Testing:     NewTestingNamespace(config),
		Application: NewApplicationNamespace(config),
		Message:     NewMessageNamespace(config),
		Other:       NewOtherNamespace(config),
		Messages:    NewMessagesNamespace(config),
		Tags:        NewTagsNamespace(config),
	}
}
