// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type GetMessagesParamsParams struct {
	Start *int64
	Limit *int64
}

// GetMessagesParams returns messages from the mailbox ordered from newest to oldest.
//
// Parameters:
//
//	start: Pagination offset
//	limit: Limit number of results
func GetMessagesParams(ctx context.Context, clientConfig ClientConfig, params GetMessagesParamsParams) (interface{}, error) {
	start := params.Start
	limit := params.Limit

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", "/api/v1/messages", &RequestOpts{
		Query: map[string]any{
			"start": QueryValue{Value: start, Style: "form", Explode: true},
			"limit": QueryValue{Value: limit, Style: "form", Explode: true},
		},
		OperationID: "GetMessagesParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type SetReadStatusParamsParams struct {
	Tz     *string
	IDs    *[]string
	Read   *bool
	Search *string
}

// SetReadStatusParams you can optionally provide an array of IDs or a search string. If neither IDs nor search is provided then all mailbox messages are updated.
//
// Parameters:
//
//	tz: Optional [timezone
//	identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
//	used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
//	iDs: Optional array of message database IDs
//	read: Read status
//	search: Optional messages matching a search
func SetReadStatusParams(ctx context.Context, clientConfig ClientConfig, params SetReadStatusParamsParams) (interface{}, error) {
	tz := params.Tz
	iDs := params.IDs
	read := params.Read
	search := params.Search

	_, err := DoEmptyCfg(ctx, &clientConfig, "PUT", "/api/v1/messages", &RequestOpts{
		Query: map[string]any{
			"tz": QueryValue{Value: tz, Style: "form", Explode: true},
		},
		Body: map[string]any{
			"IDs":    iDs,
			"Read":   read,
			"Search": search,
		},
		OperationID: "SetReadStatusParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type DeleteMessagesParamsParams struct {
	IDs *[]string
}

// DeleteMessagesParams delete individual or all messages. If no IDs are provided then all messages are deleted.
//
// Parameters:
//
//	iDs: Array of message database IDs
func DeleteMessagesParams(ctx context.Context, clientConfig ClientConfig, params DeleteMessagesParamsParams) (interface{}, error) {
	iDs := params.IDs

	_, err := DoEmptyCfg(ctx, &clientConfig, "DELETE", "/api/v1/messages", &RequestOpts{
		Body: map[string]any{
			"IDs": iDs,
		},
		OperationID: "DeleteMessagesParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type SearchParamsParams struct {
	Query string
	Start *string
	Limit *string
	Tz    *string
}

// SearchParams returns messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/), sorted by received date (descending).
//
// Parameters:
//
//	query: Search query
//	start: Pagination offset
//	limit: Limit results
//	tz: Optional [timezone
//	identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
//	used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
func SearchParams(ctx context.Context, clientConfig ClientConfig, params SearchParamsParams) (interface{}, error) {
	query := params.Query
	start := params.Start
	limit := params.Limit
	tz := params.Tz

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", "/api/v1/search", &RequestOpts{
		Query: map[string]any{
			"query": QueryValue{Value: query, Style: "form", Explode: true},
			"start": QueryValue{Value: start, Style: "form", Explode: true},
			"limit": QueryValue{Value: limit, Style: "form", Explode: true},
			"tz":    QueryValue{Value: tz, Style: "form", Explode: true},
		},
		OperationID: "SearchParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type DeleteSearchParamsParams struct {
	Query string
	Tz    *string
}

// DeleteSearchParams delete all messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/).
//
// Parameters:
//
//	query: Search query
//	tz: [Timezone
//	identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
//	used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
func DeleteSearchParams(ctx context.Context, clientConfig ClientConfig, params DeleteSearchParamsParams) (interface{}, error) {
	query := params.Query
	tz := params.Tz

	_, err := DoEmptyCfg(ctx, &clientConfig, "DELETE", "/api/v1/search", &RequestOpts{
		Query: map[string]any{
			"query": QueryValue{Value: query, Style: "form", Explode: true},
			"tz":    QueryValue{Value: tz, Style: "form", Explode: true},
		},
		OperationID: "DeleteSearchParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
