// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
	"fmt"
)

// SendMessageParamsFrom "From" recipient
type SendMessageParamsFrom struct {
	// Email Email address
	Email string `json:"Email"`
	// Name Optional name
	Name *string `json:"Name,omitempty"`
}

func (value *SendMessageParamsFrom) UnmarshalJSON(data []byte) error {
	type SendMessageParamsFromAlias SendMessageParamsFrom
	var decoded SendMessageParamsFromAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = SendMessageParamsFrom(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"Email"}); err != nil {
		return err
	}
	return nil
}

// NewSendMessageParamsFrom returns a validated SendMessageParamsFrom built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewSendMessageParamsFrom(fields SendMessageParamsFrom) (*SendMessageParamsFrom, error) {
	return ConstructModel(fields)
}

type GetMessageParamsParams struct {
	ID string
}

// GetMessageParams returns the summary of a message, marking the message as read. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func GetMessageParams(ctx context.Context, clientConfig ClientConfig, params GetMessageParamsParams) (*Message, error) {
	iD := params.ID

	resp, err := DoCfg[Message](ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s", EncodePathSegment(iD)), &RequestOpts{
		OperationID: "GetMessageParams",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetHeadersParamsParams struct {
	ID string
}

// GetHeadersParams returns the message headers as an array. Note that header keys are returned alphabetically. The ID can be set to `latest` to return the latest message headers.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func GetHeadersParams(ctx context.Context, clientConfig ClientConfig, params GetHeadersParamsParams) (interface{}, error) {
	iD := params.ID

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/headers", EncodePathSegment(iD)), &RequestOpts{
		OperationID: "GetHeadersParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type AttachmentParamsParams struct {
	ID     string
	PartID string
}

// AttachmentParams this will return the attachment part using the appropriate Content-Type. The ID can be set to `latest` to reference the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	partID: Attachment part ID
func AttachmentParams(ctx context.Context, clientConfig ClientConfig, params AttachmentParamsParams) (interface{}, error) {
	iD := params.ID
	partID := params.PartID

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/part/%s", EncodePathSegment(iD), EncodePathSegment(partID)), &RequestOpts{
		OperationID: "AttachmentParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type ThumbnailParamsParams struct {
	ID     string
	PartID string
}

// ThumbnailParams this will return a cropped 180x120 JPEG thumbnail of an image attachment. If the image is smaller than 180x120 then the image is padded. If the attachment is not an image then a blank image is returned. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	partID: Attachment part ID
func ThumbnailParams(ctx context.Context, clientConfig ClientConfig, params ThumbnailParamsParams) (interface{}, error) {
	iD := params.ID
	partID := params.PartID

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/part/%s/thumb", EncodePathSegment(iD), EncodePathSegment(partID)), &RequestOpts{
		OperationID: "ThumbnailParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type DownloadRawParamsParams struct {
	ID string
}

// DownloadRawParams returns the full email source as plain text. The ID can be set to `latest` to return the latest message source.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func DownloadRawParams(ctx context.Context, clientConfig ClientConfig, params DownloadRawParamsParams) (interface{}, error) {
	iD := params.ID

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/raw", EncodePathSegment(iD)), &RequestOpts{
		OperationID: "DownloadRawParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type ReleaseMessageParamsParams struct {
	ID string
	To []string
}

// ReleaseMessageParams release a message via a pre-configured external SMTP server. This is only enabled if message relaying has been configured. The ID can be set to `latest` to reference the latest message.
//
// Parameters:
//
//	iD: Message database ID
//	to: Array of email addresses to relay the message to
func ReleaseMessageParams(ctx context.Context, clientConfig ClientConfig, params ReleaseMessageParamsParams) (interface{}, error) {
	iD := params.ID
	to := params.To

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/api/v1/message/%s/release", EncodePathSegment(iD)), &RequestOpts{
		Body: map[string]any{
			"To": to,
		},
		OperationID: "ReleaseMessageParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type SendMessageParamsParams struct {
	From        SendMessageParamsFrom
	Attachments *[]map[string]interface{}
	Bcc         *[]string
	Cc          *[]map[string]interface{}
	HTML        *string
	Headers     *map[string]string
	ReplyTo     *[]map[string]interface{}
	Subject     *string
	Tags        *[]string
	Text        *string
	To          *[]map[string]interface{}
}

// SendMessageParams sends an email message through the HTTP API with sender, recipient, and message content details. Provide `From` with an `Email` address, and use `Attachments` for files encoded in base64. A 200 response includes the sent message's database ID.
//
// Send a message via the HTTP API.
//
// Parameters:
//
//	from: "From" recipient
//	attachments: Attachments
//	bcc: Bcc recipients email addresses only
//	cc: Cc recipients
//	hTML: Message body (HTML)
//	headers: Optional headers in {"key":"value"} format
//	replyTo: Optional Reply-To recipients
//	subject: Subject
//	tags: Mailpit tags
//	text: Message body (text)
//	to: "To" recipients
func SendMessageParams(ctx context.Context, clientConfig ClientConfig, params SendMessageParamsParams) (interface{}, error) {
	from := params.From
	attachments := params.Attachments
	bcc := params.Bcc
	cc := params.Cc
	hTML := params.HTML
	headers := params.Headers
	replyTo := params.ReplyTo
	subject := params.Subject
	tags := params.Tags
	text := params.Text
	to := params.To

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", "/api/v1/send", &RequestOpts{
		Body: map[string]any{
			"From":        from,
			"Attachments": attachments,
			"Bcc":         bcc,
			"Cc":          cc,
			"HTML":        hTML,
			"Headers":     headers,
			"ReplyTo":     replyTo,
			"Subject":     subject,
			"Tags":        tags,
			"Text":        text,
			"To":          to,
		},
		OperationID: "SendMessageParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
