// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// MessageSummary MessageSummary struct for frontend messages
type MessageSummary struct {
	// Attachments Whether the message has any attachments
	Attachments *int64 `json:"Attachments,omitempty"`
	// Bcc Bcc addresses
	Bcc []Address `json:"Bcc,omitempty"`
	// Cc Cc addresses
	Cc []Address `json:"Cc,omitempty"`
	// Created Received RFC3339Nano date & time ([extended RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) format with optional nano seconds)
	Created *string `json:"Created,omitempty"`
	// From An address such as "Barry Gibbs <bg@example.com>" is represented
	// as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
	From *Address `json:"From,omitempty"`
	// ID Database ID
	ID *string `json:"ID,omitempty"`
	// MessageID Message ID
	MessageID *string `json:"MessageID,omitempty"`
	// Read Read status
	Read *bool `json:"Read,omitempty"`
	// ReplyTo Reply-To address
	ReplyTo []Address `json:"ReplyTo,omitempty"`
	// Size Message size in bytes (total)
	Size *int64 `json:"Size,omitempty"`
	// Snippet Message snippet includes up to 250 characters
	Snippet *string `json:"Snippet,omitempty"`
	// Subject Email subject
	Subject *string `json:"Subject,omitempty"`
	// Tags Message tags
	Tags []string `json:"Tags,omitempty"`
	// To To address
	To []Address `json:"To,omitempty"`
	// Username Username used for authentication (if provided) with the SMTP or Send API
	Username *string `json:"Username,omitempty"`
}

func (value *MessageSummary) UnmarshalJSON(data []byte) error {
	type MessageSummaryAlias MessageSummary
	var decoded MessageSummaryAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = MessageSummary(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Created != nil {
		if err := ValidateDateTime("Created", *value.Created); err != nil {
			return err
		}
	}
	return nil
}

// NewMessageSummary returns a validated MessageSummary built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewMessageSummary(fields MessageSummary) (*MessageSummary, error) {
	return ConstructModel(fields)
}

// MessagesSummary MessagesSummary is a summary of a list of messages
type MessagesSummary struct {
	// Messages Messages summary
	Messages []MessageSummary `json:"messages,omitempty"`
	// MessagesCount Total number of messages matching current query
	MessagesCount *int64 `json:"messages_count,omitempty"`
	// MessagesUnread Total number of unread messages matching current query
	MessagesUnread *int64 `json:"messages_unread,omitempty"`
	// Start Pagination offset
	Start *int64 `json:"start,omitempty"`
	// Tags All current tags
	Tags []string `json:"tags,omitempty"`
	// Total Total number of messages in mailbox
	Total *int64 `json:"total,omitempty"`
	// Unread Total number of unread messages in mailbox
	Unread *int64 `json:"unread,omitempty"`
}

// NewMessagesSummary returns a validated MessagesSummary built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewMessagesSummary(fields MessagesSummary) (*MessagesSummary, error) {
	return ConstructModel(fields)
}
