// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// Address An address such as "Barry Gibbs <bg@example.com>" is represented
// as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
type Address struct {
	// Address Optional `string` value serialized in the `Address` wire field.
	Address *string `json:"Address,omitempty"`
	// Name Optional `string` value serialized in the `Name` wire field.
	Name *string `json:"Name,omitempty"`
}

// NewAddress returns a validated Address built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAddress(fields Address) (*Address, error) {
	return ConstructModel(fields)
}
