// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// Attachment Attachment struct for inline images and attachments
type Attachment struct {
	// Checksums File checksums
	Checksums *AttachmentChecksums `json:"Checksums,omitempty"`
	// ContentID Content ID
	ContentID *string `json:"ContentID,omitempty"`
	// ContentType Content type
	ContentType *string `json:"ContentType,omitempty"`
	// FileName File name
	FileName *string `json:"FileName,omitempty"`
	// PartID Attachment part ID
	PartID *string `json:"PartID,omitempty"`
	// Size Size in bytes
	Size *int64 `json:"Size,omitempty"`
}

// NewAttachment returns a validated Attachment built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAttachment(fields Attachment) (*Attachment, error) {
	return ConstructModel(fields)
}

// AttachmentChecksums File checksums
type AttachmentChecksums struct {
	// MD5 MD5 checksum hash of file
	MD5 *string `json:"MD5,omitempty"`
	// SHA1 SHA1 checksum hash of file
	SHA1 *string `json:"SHA1,omitempty"`
	// SHA256 SHA256 checksum hash of file
	SHA256 *string `json:"SHA256,omitempty"`
}

// NewAttachmentChecksums returns a validated AttachmentChecksums built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAttachmentChecksums(fields AttachmentChecksums) (*AttachmentChecksums, error) {
	return ConstructModel(fields)
}

// ListUnsubscribe ListUnsubscribe contains a summary of List-Unsubscribe & List-Unsubscribe-Post headers
// including validation of the link structure
type ListUnsubscribe struct {
	// Errors Validation errors (if any)
	Errors *string `json:"Errors,omitempty"`
	// Header List-Unsubscribe header value
	Header *string `json:"Header,omitempty"`
	// HeaderPost List-Unsubscribe-Post value (if set)
	HeaderPost *string `json:"HeaderPost,omitempty"`
	// Links Detected links, maximum one email and one HTTP(S) link
	Links []string `json:"Links,omitempty"`
}

// NewListUnsubscribe returns a validated ListUnsubscribe built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewListUnsubscribe(fields ListUnsubscribe) (*ListUnsubscribe, error) {
	return ConstructModel(fields)
}

// Message Message data excluding physical attachments
type Message struct {
	// Attachments Message attachments
	Attachments []Attachment `json:"Attachments,omitempty"`
	// Bcc Bcc addresses
	Bcc []Address `json:"Bcc,omitempty"`
	// Cc Cc addresses
	Cc []Address `json:"Cc,omitempty"`
	// Date Message RFC3339Nano date & time (if set), else date & time received
	// ([extended RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) format with optional nano seconds)
	Date *string `json:"Date,omitempty"`
	// From An address such as "Barry Gibbs <bg@example.com>" is represented
	// as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
	From *Address `json:"From,omitempty"`
	// HTML Message body HTML
	HTML *string `json:"HTML,omitempty"`
	// ID Database ID
	ID *string `json:"ID,omitempty"`
	// Inline Inline message attachments
	Inline []Attachment `json:"Inline,omitempty"`
	// ListUnsubscribe ListUnsubscribe contains a summary of List-Unsubscribe & List-Unsubscribe-Post headers
	// including validation of the link structure
	ListUnsubscribe *ListUnsubscribe `json:"ListUnsubscribe,omitempty"`
	// MessageID Message ID
	MessageID *string `json:"MessageID,omitempty"`
	// ReplyTo ReplyTo addresses
	ReplyTo []Address `json:"ReplyTo,omitempty"`
	// ReturnPath Return-Path
	ReturnPath *string `json:"ReturnPath,omitempty"`
	// Size Message size in bytes
	Size *int64 `json:"Size,omitempty"`
	// Subject Message subject
	Subject *string `json:"Subject,omitempty"`
	// Tags Message tags
	Tags []string `json:"Tags,omitempty"`
	// Text Message body text
	Text *string `json:"Text,omitempty"`
	// To To addresses
	To []Address `json:"To,omitempty"`
	// Username Username used for authentication (if provided) with the SMTP or Send API
	Username *string `json:"Username,omitempty"`
}

func (value *Message) UnmarshalJSON(data []byte) error {
	type MessageAlias Message
	var decoded MessageAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = Message(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Date != nil {
		if err := ValidateDateTime("Date", *value.Date); err != nil {
			return err
		}
	}
	return nil
}

// NewMessage returns a validated Message built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewMessage(fields Message) (*Message, error) {
	return ConstructModel(fields)
}
