// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// ChaosTrigger Trigger for Chaos
type ChaosTrigger struct {
	// ErrorCode SMTP error code to return. The value must range from 400 to 599.
	ErrorCode int64 `json:"ErrorCode"`
	// Probability Probability (chance) of triggering the error. The value must range from 0 to 100.
	Probability int64 `json:"Probability"`
}

func (value *ChaosTrigger) UnmarshalJSON(data []byte) error {
	type ChaosTriggerAlias ChaosTrigger
	var decoded ChaosTriggerAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ChaosTrigger(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"ErrorCode", "Probability"}); err != nil {
		return err
	}
	return nil
}

// NewChaosTrigger returns a validated ChaosTrigger built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewChaosTrigger(fields ChaosTrigger) (*ChaosTrigger, error) {
	return ConstructModel(fields)
}

// ChaosTriggers Triggers for the Chaos configuration
type ChaosTriggers struct {
	// Authentication Trigger for Chaos
	Authentication *ChaosTrigger `json:"Authentication,omitempty"`
	// Recipient Trigger for Chaos
	Recipient *ChaosTrigger `json:"Recipient,omitempty"`
	// Sender Trigger for Chaos
	Sender *ChaosTrigger `json:"Sender,omitempty"`
}

// NewChaosTriggers returns a validated ChaosTriggers built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewChaosTriggers(fields ChaosTriggers) (*ChaosTriggers, error) {
	return ConstructModel(fields)
}
