// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// AppInformationModel AppInformation struct
type AppInformationModel struct {
	// Database Database path
	Database *string `json:"Database,omitempty"`
	// DatabaseSize Database size in bytes
	DatabaseSize *int64 `json:"DatabaseSize,omitempty"`
	// LatestVersion Latest Mailpit version
	LatestVersion *string `json:"LatestVersion,omitempty"`
	// Messages Total number of messages in the database
	Messages *int64 `json:"Messages,omitempty"`
	// RuntimeStats Runtime statistics
	RuntimeStats *AppInformationRuntimeStats `json:"RuntimeStats,omitempty"`
	// Tags Tags and message totals per tag
	Tags map[string]int64 `json:"Tags,omitempty"`
	// Unread Total number of messages in the database
	Unread *int64 `json:"Unread,omitempty"`
	// Version Current Mailpit version
	Version *string `json:"Version,omitempty"`
}

// NewAppInformationModel returns a validated AppInformationModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppInformationModel(fields AppInformationModel) (*AppInformationModel, error) {
	return ConstructModel(fields)
}

// AppInformationRuntimeStats Runtime statistics
type AppInformationRuntimeStats struct {
	// Memory Current memory usage in bytes
	Memory *int64 `json:"Memory,omitempty"`
	// MessagesDeleted Database runtime messages deleted
	MessagesDeleted *int64 `json:"MessagesDeleted,omitempty"`
	// SMTPAccepted Accepted runtime SMTP messages
	SMTPAccepted *int64 `json:"SMTPAccepted,omitempty"`
	// SMTPAcceptedSize Total runtime accepted messages size in bytes
	SMTPAcceptedSize *int64 `json:"SMTPAcceptedSize,omitempty"`
	// SMTPIgnored Ignored runtime SMTP messages (when using --ignore-duplicate-ids)
	SMTPIgnored *int64 `json:"SMTPIgnored,omitempty"`
	// SMTPRejected Rejected runtime SMTP messages
	SMTPRejected *int64 `json:"SMTPRejected,omitempty"`
	// Uptime Mailpit server uptime in seconds
	Uptime *int64 `json:"Uptime,omitempty"`
}

// NewAppInformationRuntimeStats returns a validated AppInformationRuntimeStats built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAppInformationRuntimeStats(fields AppInformationRuntimeStats) (*AppInformationRuntimeStats, error) {
	return ConstructModel(fields)
}

// WebUIConfiguration Web UI configuration settings
type WebUIConfiguration struct {
	// ChaosEnabled Whether Chaos support is enabled at runtime
	ChaosEnabled *bool `json:"ChaosEnabled,omitempty"`
	// DuplicatesIgnored Whether messages with duplicate IDs are ignored
	DuplicatesIgnored *bool `json:"DuplicatesIgnored,omitempty"`
	// HideDeleteAllButton Whether the delete button should be hidden
	HideDeleteAllButton *bool `json:"HideDeleteAllButton,omitempty"`
	// Label Optional label to identify this Mailpit instance
	Label *string `json:"Label,omitempty"`
	// MessageRelay Message Relay information
	MessageRelay *WebUIConfigurationMessageRelay `json:"MessageRelay,omitempty"`
	// SpamAssassin Whether SpamAssassin is enabled
	SpamAssassin *bool `json:"SpamAssassin,omitempty"`
}

// NewWebUIConfiguration returns a validated WebUIConfiguration built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewWebUIConfiguration(fields WebUIConfiguration) (*WebUIConfiguration, error) {
	return ConstructModel(fields)
}

// WebUIConfigurationMessageRelay Message Relay information
type WebUIConfigurationMessageRelay struct {
	// AllowedRecipients Only allow relaying to these recipients (regex)
	AllowedRecipients *string `json:"AllowedRecipients,omitempty"`
	// BlockedRecipients Block relaying to these recipients (regex)
	BlockedRecipients *string `json:"BlockedRecipients,omitempty"`
	// Enabled Whether message relaying (release) is enabled
	Enabled *bool `json:"Enabled,omitempty"`
	// OverrideFrom Overrides the "From" address for all relayed messages
	OverrideFrom *string `json:"OverrideFrom,omitempty"`
	// PreserveMessageIDs Preserve the original Message-IDs when relaying messages
	PreserveMessageIDs *bool `json:"PreserveMessageIDs,omitempty"`
	// ReturnPath Enforced Return-Path (if set) for relay bounces
	ReturnPath *string `json:"ReturnPath,omitempty"`
	// SMTPServer The configured SMTP server address
	SMTPServer *string `json:"SMTPServer,omitempty"`
}

// NewWebUIConfigurationMessageRelay returns a validated WebUIConfigurationMessageRelay built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewWebUIConfigurationMessageRelay(fields WebUIConfigurationMessageRelay) (*WebUIConfigurationMessageRelay, error) {
	return ConstructModel(fields)
}
