// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// HTMLCheckResponse Response represents the HTML check response struct
type HTMLCheckResponse struct {
	// Platforms All platforms tested, mainly for the web UI
	Platforms map[string][]string `json:"Platforms,omitempty"`
	// Total Total weighted result for all scores
	Total *HTMLCheckTotal `json:"Total,omitempty"`
	// Warnings List of warnings from tests
	Warnings []HTMLCheckWarning `json:"Warnings,omitempty"`
}

// NewHTMLCheckResponse returns a validated HTMLCheckResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewHTMLCheckResponse(fields HTMLCheckResponse) (*HTMLCheckResponse, error) {
	return ConstructModel(fields)
}

// HTMLCheckResult Result struct
type HTMLCheckResult struct {
	// Family Family eg: Outlook, Mozilla Thunderbird
	Family *string `json:"Family,omitempty"`
	// Name Friendly name of result, combining family, platform & version
	Name *string `json:"Name,omitempty"`
	// NoteNumber Note number for partially supported if applicable
	NoteNumber *string `json:"NoteNumber,omitempty"`
	// Platform Platform eg: ios, android, windows
	Platform *string `json:"Platform,omitempty"`
	// Support Support [yes, no, partial]
	Support *string `json:"Support,omitempty"`
	// Version Family version eg: 4.7.1, 2019-10, 10.3
	Version *string `json:"Version,omitempty"`
}

// NewHTMLCheckResult returns a validated HTMLCheckResult built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewHTMLCheckResult(fields HTMLCheckResult) (*HTMLCheckResult, error) {
	return ConstructModel(fields)
}

// HTMLCheckScore Score struct
type HTMLCheckScore struct {
	// Found Number of matches in the document
	Found *int64 `json:"Found,omitempty"`
	// Partial Total percentage partially supported
	Partial *float64 `json:"Partial,omitempty"`
	// Supported Total percentage supported
	Supported *float64 `json:"Supported,omitempty"`
	// Unsupported Total percentage unsupported
	Unsupported *float64 `json:"Unsupported,omitempty"`
}

// NewHTMLCheckScore returns a validated HTMLCheckScore built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewHTMLCheckScore(fields HTMLCheckScore) (*HTMLCheckScore, error) {
	return ConstructModel(fields)
}

// HTMLCheckTotal Total weighted result for all scores
type HTMLCheckTotal struct {
	// Nodes Total number of HTML nodes detected in message
	Nodes *int64 `json:"Nodes,omitempty"`
	// Partial Overall percentage partially supported
	Partial *float64 `json:"Partial,omitempty"`
	// Supported Overall percentage supported
	Supported *float64 `json:"Supported,omitempty"`
	// Tests Total number of tests done
	Tests *int64 `json:"Tests,omitempty"`
	// Unsupported Overall percentage unsupported
	Unsupported *float64 `json:"Unsupported,omitempty"`
}

// NewHTMLCheckTotal returns a validated HTMLCheckTotal built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewHTMLCheckTotal(fields HTMLCheckTotal) (*HTMLCheckTotal, error) {
	return ConstructModel(fields)
}

// HTMLCheckWarning Warning represents a failed test
type HTMLCheckWarning struct {
	// Category Category [css, html]
	Category *string `json:"Category,omitempty"`
	// Description Description
	Description *string `json:"Description,omitempty"`
	// Keywords Keywords
	Keywords *string `json:"Keywords,omitempty"`
	// NotesByNumber Notes based on results
	NotesByNumber map[string]string `json:"NotesByNumber,omitempty"`
	// Results Test results
	Results []HTMLCheckResult `json:"Results,omitempty"`
	// Score Score struct
	Score *HTMLCheckScore `json:"Score,omitempty"`
	// Slug Slug identifier
	Slug *string `json:"Slug,omitempty"`
	// Tags Tags
	Tags []string `json:"Tags,omitempty"`
	// Title Friendly title
	Title *string `json:"Title,omitempty"`
	// URL URL to caniemail.com
	URL *string `json:"URL,omitempty"`
}

// NewHTMLCheckWarning returns a validated HTMLCheckWarning built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewHTMLCheckWarning(fields HTMLCheckWarning) (*HTMLCheckWarning, error) {
	return ConstructModel(fields)
}

// Link Link struct
type Link struct {
	// Status HTTP status definition
	Status *string `json:"Status,omitempty"`
	// StatusCode HTTP status code
	StatusCode *int64 `json:"StatusCode,omitempty"`
	// URL Link URL
	URL *string `json:"URL,omitempty"`
}

// NewLink returns a validated Link built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewLink(fields Link) (*Link, error) {
	return ConstructModel(fields)
}

// LinkCheckResponse Response represents the Link check response
type LinkCheckResponse struct {
	// Errors Total number of errors
	Errors *int64 `json:"Errors,omitempty"`
	// Links Tested links
	Links []Link `json:"Links,omitempty"`
}

// NewLinkCheckResponse returns a validated LinkCheckResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewLinkCheckResponse(fields LinkCheckResponse) (*LinkCheckResponse, error) {
	return ConstructModel(fields)
}

// Rule Rule struct
type Rule struct {
	// Description SpamAssassin rule description
	Description *string `json:"Description,omitempty"`
	// Name SpamAssassin rule name
	Name *string `json:"Name,omitempty"`
	// Score Spam rule score
	Score *float64 `json:"Score,omitempty"`
}

// NewRule returns a validated Rule built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewRule(fields Rule) (*Rule, error) {
	return ConstructModel(fields)
}

// SpamAssassinResponse Result is a SpamAssassin result
type SpamAssassinResponse struct {
	// Error If populated will return an error string
	Error *string `json:"Error,omitempty"`
	// IsSpam Whether the message is spam or not
	IsSpam *bool `json:"IsSpam,omitempty"`
	// Rules Spam rules triggered
	Rules []Rule `json:"Rules,omitempty"`
	// Score Total spam score based on triggered rules
	Score *float64 `json:"Score,omitempty"`
}

// NewSpamAssassinResponse returns a validated SpamAssassinResponse built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewSpamAssassinResponse(fields SpamAssassinResponse) (*SpamAssassinResponse, error) {
	return ConstructModel(fields)
}
