// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

type HTMLCheckParamsParams struct {
	ID string
}

// HTMLCheckParams returns the summary of the message HTML checker. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func HTMLCheckParams(ctx context.Context, clientConfig ClientConfig, params HTMLCheckParamsParams) (*HTMLCheckResponse, error) {
	iD := params.ID

	resp, err := DoCfg[HTMLCheckResponse](ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/html-check", EncodePathSegment(iD)), &RequestOpts{
		OperationID: "HTMLCheckParams",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type LinkCheckParamsParams struct {
	ID     string
	Follow *string
}

// LinkCheckParams returns the summary of the message Link checker. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	follow: Follow redirects
func LinkCheckParams(ctx context.Context, clientConfig ClientConfig, params LinkCheckParamsParams) (*LinkCheckResponse, error) {
	iD := params.ID
	follow := params.Follow

	resp, err := DoCfg[LinkCheckResponse](ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/link-check", EncodePathSegment(iD)), &RequestOpts{
		Query: map[string]any{
			"follow": QueryValue{Value: follow, Style: "form", Explode: true},
		},
		OperationID: "LinkCheckParams",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type SpamAssassinCheckParamsParams struct {
	ID string
}

// SpamAssassinCheckParams returns the SpamAssassin summary (if enabled) of the message. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func SpamAssassinCheckParams(ctx context.Context, clientConfig ClientConfig, params SpamAssassinCheckParamsParams) (*SpamAssassinResponse, error) {
	iD := params.ID

	resp, err := DoCfg[SpamAssassinResponse](ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/message/%s/sa-check", EncodePathSegment(iD)), &RequestOpts{
		OperationID: "SpamAssassinCheckParams",
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
