// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

// SdkError is the base error type for all SDK failures.
// Concrete types: SdkValidationError, SdkHttpError, SdkNetworkError, SdkTimeoutError.
type SdkError interface {
	error
	sdkErrorMarker()
}

type sdkErrorBase struct{}

func (sdkErrorBase) sdkErrorMarker() {}

// SdkValidationError is returned when a method argument fails an OpenAPI constraint
// before the request is dispatched.
type SdkValidationError struct {
	sdkErrorBase
	Field   string
	Code    string
	Message string
}

func (e *SdkValidationError) Error() string { return e.Message }

// SdkHttpError is returned for any non-2xx HTTP response.
type SdkHttpError struct {
	sdkErrorBase
	StatusCode int
	StatusText string
	Body       []byte
	Headers    map[string]string
	RequestID  string
}

func (e *SdkHttpError) Error() string {
	base := fmt.Sprintf("HTTP %d %s", e.StatusCode, e.StatusText)
	if detail := sdkHTTPErrorDetail(e.Body, e.Headers); detail != "" {
		return fmt.Sprintf("%s: %s", base, detail)
	}
	return base
}

const sdkHTTPErrorDetailLimit = 512

// sdkHTTPErrorDetail extracts a short, safe server-provided error message.
// It intentionally never adds an arbitrary response body to Error().
func sdkHTTPErrorDetail(body []byte, headers map[string]string) string {
	if len(body) == 0 {
		return ""
	}

	if json.Valid(body) {
		var object map[string]json.RawMessage
		if err := json.Unmarshal(body, &object); err == nil {
			if detail := sdkJSONErrorDetail(object); detail != "" {
				return sdkNormalizeHTTPErrorDetail(detail)
			}
		}
		return ""
	}

	if !sdkIsTextContentType(headers) || !utf8.Valid(body) {
		return ""
	}
	return sdkNormalizeHTTPErrorDetail(string(body))
}

func sdkJSONErrorDetail(object map[string]json.RawMessage) string {
	candidates := []json.RawMessage{object["message"], object["detail"]}
	if rawError, ok := object["error"]; ok {
		var nested map[string]json.RawMessage
		if err := json.Unmarshal(rawError, &nested); err == nil {
			candidates = append(candidates, nested["message"], nested["detail"])
		} else {
			candidates = append(candidates, rawError)
		}
	}

	for _, candidate := range candidates {
		var value string
		if len(candidate) > 0 && json.Unmarshal(candidate, &value) == nil {
			if detail := sdkNormalizeHTTPErrorDetail(value); detail != "" {
				return detail
			}
		}
	}
	return ""
}

func sdkIsTextContentType(headers map[string]string) bool {
	for name, value := range headers {
		if strings.EqualFold(strings.TrimSpace(name), "content-type") {
			mediaType := strings.ToLower(strings.TrimSpace(strings.SplitN(value, ";", 2)[0]))
			return mediaType == "" || strings.HasPrefix(mediaType, "text/")
		}
	}
	return true
}

func sdkNormalizeHTTPErrorDetail(value string) string {
	for _, r := range value {
		if (unicode.IsControl(r) && !unicode.IsSpace(r)) || (!unicode.IsPrint(r) && !unicode.IsSpace(r)) {
			return ""
		}
	}

	normalized := strings.Join(strings.Fields(value), " ")
	if normalized == "" {
		return ""
	}
	if utf8.RuneCountInString(normalized) <= sdkHTTPErrorDetailLimit {
		return normalized
	}

	return string([]rune(normalized)[:sdkHTTPErrorDetailLimit]) + "…"
}

// SdkNetworkError wraps connection / DNS / socket failures.
type SdkNetworkError struct {
	sdkErrorBase
	Cause     error
	RequestID string
}

func (e *SdkNetworkError) Error() string { return e.Cause.Error() }
func (e *SdkNetworkError) Unwrap() error { return e.Cause }

// SdkTimeoutError is returned when a request exceeds its configured timeout.
type SdkTimeoutError struct {
	sdkErrorBase
	Elapsed   time.Duration
	RequestID string
}

func (e *SdkTimeoutError) Error() string {
	return fmt.Sprintf("request timed out after %s", e.Elapsed)
}
