// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"encoding/json"
	"fmt"
	"time"
)

// ValidateRequired rejects decoded objects that omit a required wire member.
func ValidateRequired(fields map[string]json.RawMessage, required []string) error {
	for _, field := range required {
		if _, ok := fields[field]; !ok {
			return &SdkValidationError{
				Field:   field,
				Code:    "required",
				Message: fmt.Sprintf("Missing required property '%s'", field),
			}
		}
	}
	return nil
}

// ValidateDateTime enforces RFC-3339 / ISO-8601 date-time.
func ValidateDateTime(field, value string) error {
	if _, err := time.Parse(time.RFC3339, value); err != nil {
		return &SdkValidationError{Field: field, Code: "format:date-time", Message: fmt.Sprintf("Validation failed for '%s': must be a valid ISO 8601 date-time", field)}
	}
	return nil
}
