// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
)

// ClientAuthConfig holds explicit request headers and optional credentials.
type ClientAuthConfig struct {
	Headers map[string]string
}

// SdkAuthError reports that the selected authentication capability cannot
// satisfy an operation's declared security requirement.
type SdkAuthError struct {
	sdkErrorBase
	OperationID string
	Preference  string
	Message     string
}

func (e *SdkAuthError) Error() string { return e.Message }

var operationSecurity = map[string][][]string{
	"GetChaos":                   [][]string{},
	"SetChaosParams":             [][]string{},
	"AppInformation":             [][]string{},
	"GetMessageParams":           [][]string{},
	"GetHeadersParams":           [][]string{},
	"HTMLCheckParams":            [][]string{},
	"LinkCheckParams":            [][]string{},
	"AttachmentParams":           [][]string{},
	"ThumbnailParams":            [][]string{},
	"DownloadRawParams":          [][]string{},
	"ReleaseMessageParams":       [][]string{},
	"SpamAssassinCheckParams":    [][]string{},
	"GetMessagesParams":          [][]string{},
	"SetReadStatusParams":        [][]string{},
	"DeleteMessagesParams":       [][]string{},
	"SearchParams":               [][]string{},
	"DeleteSearchParams":         [][]string{},
	"SendMessageParams":          [][]string{},
	"GetAllTags":                 [][]string{},
	"SetTagsParams":              [][]string{},
	"RenameTagParams":            [][]string{},
	"DeleteTagParams":            [][]string{},
	"WebUIConfigurationResponse": [][]string{},
	"GetMessageHTMLParams":       [][]string{},
	"GetMessageTextParams":       [][]string{},
}

const defaultBaseURL = ""

// applyAuth attaches credentials to the outgoing request. Selection-aware
// modes validate the current operation before applying any scheme.
func applyAuth(ctx context.Context, cfg *ClientConfig, headers map[string]string, query map[string]any, operationID string) error {

	if security, known := operationSecurity[operationID]; known {
		for _, alternative := range security {
			if len(alternative) == 0 {
				return nil
			}
		}
		if len(security) > 0 {
			return &SdkAuthError{
				OperationID: operationID,
				Preference:  "none",
				Message:     "auth none cannot satisfy the security requirement for operation " + operationID,
			}
		}
		return nil
	}
	return nil

}
