// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

// GetAllTags lists all unique tags currently assigned to messages. Use this endpoint to retrieve the available tag values when you need to inspect message tags.
//
// Returns a JSON array of all unique message tags.
func GetAllTags(ctx context.Context, clientConfig ClientConfig) (interface{}, error) {

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", "/api/v1/tags", &RequestOpts{
		OperationID: "GetAllTags",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type SetTagsParamsParams struct {
	IDs  []string
	Tags []string
}

// SetTagsParams this will overwrite any existing tags for selected message database IDs. To remove all tags from a message, pass an empty tags array.
//
// Parameters:
//
//	iDs: Array of message database IDs
//	tags: Array of tag names to set
func SetTagsParams(ctx context.Context, clientConfig ClientConfig, params SetTagsParamsParams) (interface{}, error) {
	iDs := params.IDs
	tags := params.Tags

	_, err := DoEmptyCfg(ctx, &clientConfig, "PUT", "/api/v1/tags", &RequestOpts{
		Body: map[string]any{
			"IDs":  iDs,
			"Tags": tags,
		},
		OperationID: "SetTagsParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type RenameTagParamsParams struct {
	Tag  string
	Name string
}

// RenameTagParams renames an existing tag. Use `Tag` to identify the tag and provide `Name` as its replacement name. The request body is optional, but when supplied it must include `Name`.
//
// Renames an existing tag.
//
// Parameters:
//
//	tag: The url-encoded tag name to rename
//	name: New name
func RenameTagParams(ctx context.Context, clientConfig ClientConfig, params RenameTagParamsParams) (interface{}, error) {
	tag := params.Tag
	name := params.Name

	_, err := DoEmptyCfg(ctx, &clientConfig, "PUT", fmt.Sprintf("/api/v1/tags/%s", EncodePathSegment(tag)), &RequestOpts{
		Body: map[string]any{
			"Name": name,
		},
		OperationID: "RenameTagParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type DeleteTagParamsParams struct {
	Tag string
}

// DeleteTagParams deletes a tag. This will not delete any messages with the tag, but will remove the tag from any messages containing the tag.
//
// Parameters:
//
//	tag: The url-encoded tag name to delete
func DeleteTagParams(ctx context.Context, clientConfig ClientConfig, params DeleteTagParamsParams) (interface{}, error) {
	tag := params.Tag

	_, err := DoEmptyCfg(ctx, &clientConfig, "DELETE", fmt.Sprintf("/api/v1/tags/%s", EncodePathSegment(tag)), &RequestOpts{
		OperationID: "DeleteTagParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
