// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

// GetChaos returns the current Chaos triggers configuration. This API route will return an error if Chaos is not enabled at runtime.
func GetChaos(ctx context.Context, clientConfig ClientConfig) (interface{}, error) {

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", "/api/v1/chaos", &RequestOpts{
		OperationID: "GetChaos",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type SetChaosParamsParams struct {
	Authentication *ChaosTrigger
	Recipient      *ChaosTrigger
	Sender         *ChaosTrigger
}

// SetChaosParams set the Chaos triggers configuration and return the updated values. This API route will return an error if Chaos is not enabled at runtime. If any triggers are omitted from the request, then those are reset to their default values with a 0% probability (ie: disabled). Setting a blank `{}` will reset all triggers to their default values.
//
// Parameters:
//
//	authentication: Trigger for Chaos
//	recipient: Trigger for Chaos
//	sender: Trigger for Chaos
func SetChaosParams(ctx context.Context, clientConfig ClientConfig, params SetChaosParamsParams) (interface{}, error) {
	authentication := params.Authentication
	recipient := params.Recipient
	sender := params.Sender

	_, err := DoEmptyCfg(ctx, &clientConfig, "PUT", "/api/v1/chaos", &RequestOpts{
		Body: map[string]any{
			"Authentication": authentication,
			"Recipient":      recipient,
			"Sender":         sender,
		},
		OperationID: "SetChaosParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type GetMessageHTMLParamsParams struct {
	ID    string
	Embed *string
}

// GetMessageHTMLParams renders just the message's HTML part which can be used for UI integration testing. Attached inline images are modified to link to the API provided they exist. Note that is the message does not contain a HTML part then an 404 error is returned. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
//	embed: If this is route is to be embedded in an iframe, set embed to `1` in
//	the URL to add `target="_blank"` and `rel="noreferrer noopener"` to all
//	links. In addition, a small script will be added to the end of the document
//	to post (postMessage()) the height of the document back to the parent window
//	for optional iframe height resizing. Note that this will also *transform*
//	the message into a full HTML document (if it isn't already), so this option
//	is useful for viewing but not programmatic testing.
func GetMessageHTMLParams(ctx context.Context, clientConfig ClientConfig, params GetMessageHTMLParamsParams) (interface{}, error) {
	iD := params.ID
	embed := params.Embed

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", fmt.Sprintf("/view/%s.html", EncodePathSegment(iD)), &RequestOpts{
		Query: map[string]any{
			"embed": QueryValue{Value: embed, Style: "form", Explode: true},
		},
		OperationID: "GetMessageHTMLParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type GetMessageTextParamsParams struct {
	ID string
}

// GetMessageTextParams renders just the message's text part which can be used for UI integration testing. The ID can be set to `latest` to return the latest message.
//
// Parameters:
//
//	iD: Message database ID or "latest"
func GetMessageTextParams(ctx context.Context, clientConfig ClientConfig, params GetMessageTextParamsParams) (interface{}, error) {
	iD := params.ID

	_, err := DoEmptyCfg(ctx, &clientConfig, "GET", fmt.Sprintf("/view/%s.txt", EncodePathSegment(iD)), &RequestOpts{
		OperationID: "GetMessageTextParams",
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
